version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work


  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work


  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8082:80
    environment:
      MYSQL_ROOT_PASSWORD: secret
      PMA_HOST: db
      # PMA_USER: root
      # PMS_PASSWORD: secret

volumes:
  db-store: